<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace Thecodebunny\eBayApi\Trading\Types;

/**
 *
 * @property \Thecodebunny\eBayApi\Trading\Types\ApplicationDeliveryPreferencesType $ApplicationDeliveryPreferences
 * @property \Thecodebunny\eBayApi\Trading\Types\NotificationEnableArrayType $UserDeliveryPreferenceArray
 * @property \Thecodebunny\eBayApi\Trading\Types\NotificationUserDataType $UserData
 * @property \Thecodebunny\eBayApi\Trading\Types\NotificationEventPropertyType[] $EventProperty
 * @property string $DeliveryURLName
 */
class SetNotificationPreferencesRequestType extends \Thecodebunny\eBayApi\Trading\Types\AbstractRequestType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'ApplicationDeliveryPreferences' => [
            'type' => 'Thecodebunny\eBayApi\Trading\Types\ApplicationDeliveryPreferencesType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ApplicationDeliveryPreferences'
        ],
        'UserDeliveryPreferenceArray' => [
            'type' => 'Thecodebunny\eBayApi\Trading\Types\NotificationEnableArrayType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'UserDeliveryPreferenceArray'
        ],
        'UserData' => [
            'type' => 'Thecodebunny\eBayApi\Trading\Types\NotificationUserDataType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'UserData'
        ],
        'EventProperty' => [
            'type' => 'Thecodebunny\eBayApi\Trading\Types\NotificationEventPropertyType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'EventProperty'
        ],
        'DeliveryURLName' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'DeliveryURLName'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        if (!array_key_exists(__CLASS__, self::$requestXmlRootElementNames)) {
            self::$requestXmlRootElementNames[__CLASS__] = 'SetNotificationPreferencesRequest';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
