<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace Thecodebunny\eBayApi\Finding\Enums;

class PriceTreatmentEnum
{
    const C_MAP = 'MAP';
    const C_STP = 'STP';
}
