<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace Thecodebunny\eBayApi\MerchantData\Enums;

class ShippingServiceType
{
    const C_DOMESTIC = 'Domestic';
    const C_INTERNATIONAL = 'International';
}
