<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace Thecodebunny\eBayApi\PostOrder\Enums;

class CaseTypeEnum
{
    const C_ITEM_NOT_RECEIVED = 'ITEM_NOT_RECEIVED';
    const C_RETURN = 'RETURN';
}
