<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace Thecodebunny\eBayApi\PostOrder\Enums;

class RuleListFieldGroupEnum
{
    const C_FULL = 'FULL';
    const C_NONE = 'NONE';
    const C_SUMMARY = 'SUMMARY';
}
