<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace Thecodebunny\eBayApi\HalfFinding\Enums;

class Type
{
    const C_SHIPPING_METHOD_EXPRESS = 'ShippingMethodExpress';
    const C_SHIPPING_METHOD_STANDARD = 'ShippingMethodStandard';
}
