<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace Thecodebunny\eBayApi\ResolutionCaseManagement\Types;

/**
 *
 * @property \Thecodebunny\eBayApi\ResolutionCaseManagement\Enums\MoneyMovementType $type
 * @property \Thecodebunny\eBayApi\ResolutionCaseManagement\Types\CaseUserType $fromParty
 * @property \Thecodebunny\eBayApi\ResolutionCaseManagement\Types\CaseUserType $toParty
 * @property \Thecodebunny\eBayApi\ResolutionCaseManagement\Types\Amount $amount
 * @property \Thecodebunny\eBayApi\ResolutionCaseManagement\Enums\PaymentMethodType $paymentMethod
 * @property string $paypalTransactionId
 * @property \Thecodebunny\eBayApi\ResolutionCaseManagement\Enums\MoneyMovementStatusType $status
 * @property \DateTime $transactionDate
 * @property string $id
 * @property string $parentId
 */
class MoneyMovementDetailType extends \Thecodebunny\eBayApi\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'type' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'type'
        ],
        'fromParty' => [
            'type' => 'Thecodebunny\eBayApi\ResolutionCaseManagement\Types\CaseUserType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'fromParty'
        ],
        'toParty' => [
            'type' => 'Thecodebunny\eBayApi\ResolutionCaseManagement\Types\CaseUserType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'toParty'
        ],
        'amount' => [
            'type' => 'Thecodebunny\eBayApi\ResolutionCaseManagement\Types\Amount',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'amount'
        ],
        'paymentMethod' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'paymentMethod'
        ],
        'paypalTransactionId' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'paypalTransactionId'
        ],
        'status' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'status'
        ],
        'transactionDate' => [
            'type' => 'DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'transactionDate'
        ],
        'id' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => true,
            'attributeName' => 'id'
        ],
        'parentId' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => true,
            'attributeName' => 'parentId'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="http://www.ebay.com/marketplace/resolution/v1/services"';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
