<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace Thecodebunny\eBayApi\ResolutionCaseManagement\Types;

/**
 *
 * @property \Thecodebunny\eBayApi\ResolutionCaseManagement\Types\CaseIdType $caseId
 * @property \Thecodebunny\eBayApi\ResolutionCaseManagement\Enums\ProofType $proofType
 * @property \Thecodebunny\eBayApi\ResolutionCaseManagement\Types\UploadDocumentInfoType[] $document
 */
class UploadDocumentsRequest extends \Thecodebunny\eBayApi\ResolutionCaseManagement\Types\BaseRequest
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'caseId' => [
            'type' => 'Thecodebunny\eBayApi\ResolutionCaseManagement\Types\CaseIdType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'caseId'
        ],
        'proofType' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'proofType'
        ],
        'document' => [
            'type' => 'Thecodebunny\eBayApi\ResolutionCaseManagement\Types\UploadDocumentInfoType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'document'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="http://www.ebay.com/marketplace/resolution/v1/services"';
        }

        if (!array_key_exists(__CLASS__, self::$requestXmlRootElementNames)) {
            self::$requestXmlRootElementNames[__CLASS__] = 'uploadDocumentsRequest';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
